risk-ppo:
    env: Gridworld
    run: PPO
    stop:
        training_iteration: 50
    config:
        env_config:
            grid_path: .\resources\grids\grid_alternating.json
            root: null
            timeout: 0.1
        use_gae: true
        use_critic: true
        num_workers: 0
        framework: torch
        log_level: ERROR
