risk-ppo:
    env: Gridworld
    run: PPO-RISK
    name: GRD PPO RAA SMAX

    samples: 1

    stop:
        training_iteration: 600

    config:
        model:
            custom_model_config:
                risk_factor: 8
                risk_lr: 0.00005
                risk_net_layers: [32]

        env_config:
            grid_path: .\resources\grids\grid_alternating.json
            root: null
            timeout: 0.1
            meta_actions: true
            softmax_actions: true

        use_gae: true
        use_critic: true
        num_workers: 1
        num_gpus: 0.5
        framework: torch
        log_level: ERROR

        normalize_actions: false
