risk-ppo:
    env: Gridworld
    run: PPO-RISK
    name: GRD PPO RAA META

    samples: 1

    stop:
        training_iteration: 100

    config:
        model:
            custom_action_dist: Dirichlet
            custom_model_config:
                # risk_factor: 8
                # with risk = 0.25 only the safe route is taken
                risk_factor: tune.grid_search([0.25, 0.5, 0.75, 1, 2])
                risk_lr: 0.00005
                risk_net_layers: [32]

        env_config:
            grid_path: .\resources\grids\grid_alternating.json
            root: null
            timeout: 0.1
            meta_actions: true
            softmax_actions: false

        use_gae: true
        use_critic: true
        num_workers: 1
        num_gpus: 0.1
        framework: torch
        log_level: ERROR

        normalize_actions: false
