risk-ppo:
    env: Gridworld
    run: PPO-RISK
    stop:
        training_iteration: 50
    config:
        model:
            custom_action_dist: Dirichlet
            custom_model_config:
                risk_factor: 0.06
                risk_lr: 0.00005
        env_config:
            grid_path: .\resources\grids\grid_target_choice.json
            root: null
            timeout: 0.1
            meta_actions: true
        normalize_actions: false
        use_gae: true
        use_critic: true
        num_workers: 0
        framework: torch
        log_level: ERROR
