risk-ppo:
    env: DecentralizedMarket
    run: PPO-RA-STRATEGY
    name: DEMRK PPO ATT RAS NOFEE

    samples: 1

    stop:
        training_iteration: 20000

    config:
        model:
            use_attention: true
            custom_model_config:
                risk_factor: 1
                risk_lr: 0.00001
                risk_stack_size: 80
                risk_net_layers: [32, 16]

        env_config:
            starting_funds: 100.0
            fee_model: no_fee

        gamma: 0.99
        lr: 0.0001
        lambda: 1.0
        kl_coeff: 0.2
        vf_loss_coeff: 1.0
        entropy_coeff: 0.0
        clip_param: 0.3
        vf_clip_param: 10.0

        use_gae: true
        use_critic: true
        batch_mode: complete_episodes
        num_gpus: 0.99
        num_workers: 0
        framework: torch
        log_level: ERROR
