risk-ppo:
    env: Gridworld
    run: PPO-RISK
    stop:
        training_iteration: 50
    config:
        model:
            custom_action_dist: Dirichlet
        env_config:
            grid_path: .\resources\grids\grid_default.json
            root: null
            timeout: 0.1
        normalize_actions: false
        use_gae: true
        use_critic: true
        num_workers: 0
        framework: torch
