risk-ppo:
    env: Market
    run: PPO-RISK
    name: MRK PPO ATT RAA

    samples: 2

    stop:
        training_iteration: 5000
        # training_iteration: 3

    config:
        model:
            use_attention: true
            custom_model_config:
                risk_factor: 0.1
                risk_lr: 0.00005
                risk_net_layers: [32, 16]

        env_config:
            data_path: .\resources\marketdata\data.csv
            root: null
            timeout: 0
            transaction_fee: 0.002
            episode_length: 288
            validation_length: 8928
            validation_step: 288
            is_validation: false
            validation_output: .\checkpoints\validation_ppo_attention_raactions.csv
            meta_actions: false

        gamma: 0.99
        lr: 0.0004
        lambda: 0.8
        kl_coeff: 0.2
        vf_loss_coeff: 1.0
        entropy_coeff: 0.015
        clip_param: 0.2
        vf_clip_param: 9

        use_gae: true
        use_critic: true
        batch_mode: complete_episodes
        num_gpus: 0.49
        num_workers: 5
        framework: torch
        log_level: ERROR
