risk-ppo:
    env: Market
    run: PPO-RA-STRATEGY
    stop:
        training_iteration: 15
    config:
        model:
            use_attention: true
            custom_model_config:
                risk_factor: 1
                risk_lr: 0.00001
                risk_stack_size: 80

        env_config:
            data_path: .\resources\marketdata\data.csv
            root: null
            timeout: 0
            transaction_fee: 0.002
            episode_length: 288
            validation_length: 8928
            validation_step: 288
            is_validation: false
            validation_output: .\checkpoints\validation_output_market_rastrategy_attention_ppo.csv

        gamma: 0.99
        lr: 0.0001

        normalize_actions: true
        use_gae: true
        use_critic: true
        num_gpus: 1
        num_workers: 8
        framework: torch
        log_level: ERROR
