risk-ppo:
    env: Market
    run: PPO
    stop:
        training_iteration: 500
    config:
        env_config:
            data_path: .\resources\marketdata\data.csv
            root: null
            timeout: 0
            transaction_fee: 0.002
            episode_length: 288
            validation_length: 8928
            validation_step: 288
            is_validation: false
            validation_output: .\checkpoints\validation_output_market_attention_ppo.csv

        model:
            use_attention: true

        gamma: 0.99
        lr: 0.0001

        use_gae: true
        use_critic: true
        num_gpus: 1
        num_workers: 8
        framework: torch
        log_level: ERROR
