risk-ppo:
    env: Market
    run: PPO-RISK
    stop:
        training_iteration: 5
    config:
        model:
            use_attention: true
            custom_action_dist: Dirichlet
            custom_model_config:
                risk_factor: 1
                risk_lr: 0.00005
        env_config:
            data_path: .\resources\marketdata\data.csv
            root: null
            timeout: 0
            transaction_fee: 0.002
            episode_length: 288
            validation_length: 8928
            validation_step: 288
            is_validation: false
            validation_output: .\checkpoints\validation_output_market_risk_attention_meta_ppo.csv
            meta_actions: true

        gamma: 0.99
        lr: 0.0001
        rollout_fragment_length: 287
        train_batch_size: 2870

        normalize_actions: false
        use_gae: true
        use_critic: true
        num_gpus: 1
        num_workers: 8
        framework: torch
        log_level: ERROR
